### ISSUE TITLE
Devices: update status for vegetalte, piccolo, paella

### ISSUE THREAD

**Issue by bernhardreiter** [aquaris-dev/aquaris-dev.github.io#16]
https://github.com/aquaris-dev/aquaris-dev.github.io/blob/6da5659d12739a7cc91d3ee8907ffde0765ac031/devices.md

lists the following devices as supported, where the link on the official LineageOS
says, they have been discontinued:

* [Aquaris E5 LTE](https://wiki.lineageos.org/devices/vegetalte) (vegetalte)
* [Aquaris M5](https://wiki.lineageos.org/devices/piccolo) (piccolo)
* [Aquaris X5](https://wiki.lineageos.org/devices/paella) (paella)

**Comment by stucki** [comment]
Thanks for reporting, you are right. See https://github.com/aquaris-dev/aquaris-dev.github.io/pull/17
